name = "AudioPlugins"
uuid = "83119930-5344-4127-8689-15f5870d6d1a"
authors = ["JuliaHub, Inc. and contributors"]
version = "1.1.2"

[deps]
CLAPHost_jll = "c9c4f589-041a-5a1c-a149-a4cdc6e5211b"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
JuliaC = "acedd4c2-ced6-4a15-accc-2607eb759ba2"

[extensions]
AudioPluginsJuliaCExt = "JuliaC"

[compat]
CLAPHost_jll = "1.0"
JuliaC = "0.3"
Libdl = "1"
SafeTestsets = "0.1"
SciMLTesting = "2.13"
Scratch = "1"
TOML = "1"
Test = "1"
julia = "1.10"

[extras]
JuliaC = "acedd4c2-ced6-4a15-accc-2607eb759ba2"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLTesting = "09d9d899-5365-40a9-917a-5f67fddea283"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JuliaC", "Libdl", "SafeTestsets", "SciMLTesting", "Test"]
